### ISSUE TITLE
Quick start - Content EPIC

### ISSUE THREAD

**Issue by LadyNaggaga** [Minimal-APIs/minimal-apis.github.io#17]
What would you like see:

- [x] Documentation

This issue is intended to capture the content needed for the minimal APIs quick start.  These quick starts are designed to provide developers with a brief overview of features and a how-to guide to different parts of minimal APIs.  The TOC listed isn't in priority 

What kind of content are you looking for ?

- [x] Starting a project (structure explanation)
- [x] Simple hello world (API)
- [ ] #19
- [x] #43
- [ ] #48
- [ ] Returning responses
   - [ ] #20 
   - [ ] #21
   - [ ] text 
   - [ ] custom 
   - [ ] binary files 
- [ ] Understanding #42
- [ ] #23
- [x] Adding open API (Swagger)
- [x] #24
- [ ] #25
- [ ] #26
- [ ] #27
- [ ] #29
- [ ] #41
- [ ] #38
- [ ] #30
- [x] #31
- [ ] #32
- [x] #33 
- [ ] #44

More topics 
- [ ] #39
- [ ] #40

For inspiration please looks at 
- [Flask Quickstarts](https://flask.palletsprojects.com/en/2.0.x/quickstart/)
- [Rust](https://doc.rust-lang.org/stable/rust-by-example/)

**Comment by halter73** [comment]
@LadyNaggaga I can't edit the issue, but I think we can add #33 to the list.

**Comment by LadyNaggaga** [comment]
> @LadyNaggaga I can't edit the issue, but I think we can add #33 to the list.

Added to the list
